// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYxmM-WsexbnXFbxmItHAxRUK0UA2Sa4',
    appId: '1:984231457254:web:d0839cc4187ea67f09a627',
    messagingSenderId: '984231457254',
    projectId: 'meus-gastos-8fc37',
    authDomain: 'meus-gastos-8fc37.firebaseapp.com',
    storageBucket: 'meus-gastos-8fc37.firebasestorage.app',
    measurementId: 'G-WGPVX4ZZ4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE_nqZ0JE-Lbz8uPSR3uhA9Zz2hmE5pw8',
    appId: '1:984231457254:android:30b946361ac389e909a627',
    messagingSenderId: '984231457254',
    projectId: 'meus-gastos-8fc37',
    storageBucket: 'meus-gastos-8fc37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK5ni4aN2o2q8NEh9vdd-z97BaOClJmZk',
    appId: '1:984231457254:ios:778dd66f18381add09a627',
    messagingSenderId: '984231457254',
    projectId: 'meus-gastos-8fc37',
    storageBucket: 'meus-gastos-8fc37.firebasestorage.app',
    androidClientId: '984231457254-chafmtqg5g9ca3tr6oghpu3guk239ihv.apps.googleusercontent.com',
    iosClientId: '984231457254-p0hedpgojfqothrgmpumbjp5elcmb3c4.apps.googleusercontent.com',
    iosBundleId: 'com.gambit.meusgastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK5ni4aN2o2q8NEh9vdd-z97BaOClJmZk',
    appId: '1:984231457254:ios:73e7c03c80bd6f4409a627',
    messagingSenderId: '984231457254',
    projectId: 'meus-gastos-8fc37',
    storageBucket: 'meus-gastos-8fc37.firebasestorage.app',
    androidClientId: '984231457254-chafmtqg5g9ca3tr6oghpu3guk239ihv.apps.googleusercontent.com',
    iosClientId: '984231457254-cd3t1b4e9oolfqlv34m94jrs7ai0tocu.apps.googleusercontent.com',
    iosBundleId: 'com.gambit.meusgastos.meusGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUYxmM-WsexbnXFbxmItHAxRUK0UA2Sa4',
    appId: '1:984231457254:web:c44b135a0e2ae54e09a627',
    messagingSenderId: '984231457254',
    projectId: 'meus-gastos-8fc37',
    authDomain: 'meus-gastos-8fc37.firebaseapp.com',
    storageBucket: 'meus-gastos-8fc37.firebasestorage.app',
    measurementId: 'G-D05YQGLCRY',
  );

}