name: meus_gastos
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+8

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  cupertino_icons: ^1.0.6
  flutter_masked_text2: ^0.9.0
  shared_preferences: ^2.0.6
  font_awesome_flutter: ^9.2.0
  uuid: ^3.0.5
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^20.1.55
  percent_indicator: ^4.0.0
  flutter_colorpicker: ^1.0.3
  in_app_review: ^2.0.4
  google_mobile_ads: ^3.0.0
  excel: ^4.0.6
  syncfusion_flutter_pdf: ^20.4.54
  path_provider: ^2.1.4
  open_filex: ^4.0.0
  share_plus: ^6.1.0
  tutorial_coach_mark: ^1.2.11
  in_app_purchase: ^3.0.6

  
dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: MaterialIcons

dependency_overrides:
  win32: ^5.5.4