name: meus_gastos
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+65

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  flutter_masked_text2: ^0.9.0
  shared_preferences: ^2.0.6
  font_awesome_flutter: ^10.7.0
  uuid: ^4.5.1
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^29.2.4
  percent_indicator: ^4.0.0
  flutter_colorpicker: ^1.0.3
  in_app_review: ^2.0.4
  google_mobile_ads: ^6.0.0
  excel: ^4.0.6
  syncfusion_flutter_pdf: ^29.2.4
  path_provider: ^2.1.4
  open_file: ^3.2.1
  share_plus: ^11.0.0
  tutorial_coach_mark: ^1.2.11
  in_app_purchase: ^3.2.0
  onepref: ^0.0.17
  file_picker: ^10.1.9
  table_calendar: ^3.0.7
  app_tracking_transparency: ^2.0.4
  window_size: ^0.1.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0 
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.2.2
  firebase_database: ^11.3.4
  flutter_gen: ^5.10.0
  

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

dependency_overrides:
  win32: ^5.5.4
